@extends('layouts.app')@section('title', 'Tanya Jawab - Hipertensi Non-Kehamilan')@section('content')
<section class="py-5 faq-section"><div class="container px-4"><!-- Header Section --><div class="text-center mb-5"><h2 class="fw-bolder mb-3" style="color:#0b5e91;">Hipertensi Non-Kehamilan</h2><p class="lead text-muted mx-auto" style="font-family:'Open Sans', sans-serif;max-width:700px;margin:0 auto;">
Temukan jawaban untuk pertanyaan umum tentang hipertensi pada umumnya
</p><div class="d-flex justify-content-center mt-3"><div style="width:80px;height:4px;background:linear-gradient(90deg, #0b5e91, #baa971);border-radius:2px;"></div></div></div><div class="row gx-5"><!-- FAQ Content --><div class="col-lg-8"><!-- Search Bar --><div class="faq-search mb-5"><div class="input-group"><span class="input-group-text bg-white border-end-0"><i class="bi bi-search"></i></span><input type="text" id="faqSearch" class="form-control border-start-0" placeholder="Cari pertanyaan..."></div></div><!-- FAQ Accordion: Hipertensi Non-Kehamilan --><div class="faq-group mb-5" id="hipertensi-non-kehamilan"><div class="faq-group-header"><h2 class="fw-bold">
Pertanyaan Seputar Hipertensi Non-Kehamilan
</h2><p class="text-muted">Informasi tentang hipertensi pada umumnya (bukan saat kehamilan)</p></div><div class="accordion custom-accordion" id="accordionHipertensiNonKehamilan">
@foreach ($faqs as $faq)
<div class="accordion-item"><h3 class="accordion-header" id="heading{{ $loop->index }}"><button class="accordion-button {{ $loop->first ? '' : 'collapsed' }}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ $loop->index }}" aria-expanded="{{ $loop->first ? 'true' : 'false' }}" aria-controls="collapse{{ $loop->index }}">
{{ $faq->question }}
</button></h3><div class="accordion-collapse collapse {{ $loop->first ? 'show' : '' }}" id="collapse{{ $loop->index }}" aria-labelledby="heading{{ $loop->index }}" data-bs-parent="#accordionHipertensiNonKehamilan"><div class="accordion-body"><p>{{ $faq->answer }}</p></div></div></div>
@endforeach
</div></div><!-- Still Have Questions --><div class="still-have-questions text-center p-4 rounded-4"><h3 class="fw-bold mb-3">Masih Punya Pertanyaan?</h3><p class="mb-4">Jika Anda tidak menemukan jawaban yang Anda cari, jangan ragu untuk menghubungi kami.</p><a href="mailto:klikfarmasi.official@gmail.com" class="btn btn-khusus"><i class="bi bi-envelope me-2"></i> Hubungi Kami
</a></div></div><!-- Sidebar --><div class="col-lg-4"><div class="sticky-top" style="top:2rem;z-index:1000;"><!-- Quick Help Card --><div class="card border-0 rounded-4 shadow-sm mb-4"><div class="card-header text-white py-3 border-0" style="background-color:#0b5e91;"><h5 class="mb-0 fw-bold" style="color:#fff"><i class="bi bi-info-circle me-2"></i> Bantuan Cepat</h5></div><div class="card-body p-4"><p class="card-text">Temukan jawaban cepat untuk pertanyaan tentang hipertensi non-kehamilan.</p><div class="quick-links"><a href="{{ route('tanya-jawab.kehamilan') }}" class="quick-link"><span>Hipertensi Kehamilan</span></a><a href="#hipertensi-non-kehamilan" class="quick-link"><span>Hipertensi umum</span></a></div></div></div><!-- Contact Card --><div class="card border-0 rounded-4 shadow-sm"><div class="card-body p-4"><div class="text-center mb-4"><div class="icon-circle text-white mx-auto mb-3" style="background-color:#0b5e91"><i class="bi bi-chat-dots-fill"></i></div><h5 class="fw-bold">Punya Pertanyaan?</h5><p class="text-muted mb-0">Jangan ragu untuk menghubungi kami jika Anda memiliki pertanyaan atau membutuhkan bantuan.</p></div><a href="mailto:klikfarmasi.official@gmail.com" class="btn btn-khusus w-100 mb-3"><i class="bi bi-envelope me-2"></i> Email Kami
</a><a href="https://wa.me/+6285280909235" class="btn btn-success w-100"><i class="bi bi-whatsapp me-2"></i> WhatsApp
</a><hr class="my-4"><h5 class="fw-bold text-center mb-3">Ikuti Kami</h5><div class="d-flex justify-content-center gap-3"><a class="social-icon" href="https://wa.me/+6285280909235" target="_blank"><i class="bi bi-whatsapp"></i></a><a class="social-icon" href="https://www.instagram.com/klikfarmasi.official/" target="_blank"><i class="bi bi-instagram"></i></a><a class="social-icon" href="https://www.tiktok.com/@klikfarmasi.official" target="_blank"><i class="bi bi-tiktok"></i></a><a class="social-icon" href="mailto:klikfarmasi.official@gmail.com"><i class="bi bi-envelope"></i></a></div></div></div></div></div></div></div></section>@endsection