{{-- Drug options for Godean Puskesmas --}}
<option value="Verapamil tab 80 mg">Verapamil tab 80 mg</option>
<option value="Verapamil tab lepas lambat 240 mg">Verapamil tab lepas lambat 240 mg</option>
<option value="Valsartan tab 80 mg">Valsartan tab 80 mg</option>
<option value="Valsartan tab 160 mg">Valsartan tab 160 mg</option>
<option value="Telmisartan tab 40 mg">Telmisartan tab 40 mg</option>
<option value="Telmisartan tab 80 mg">Telmisartan tab 80 mg</option>
<option value="Ramipril tab 2,5 mg">Ramipril tab 2,5 mg</option>
<option value="Ramipril tab 5 mg">Ramipril tab 5 mg</option>
<option value="Amlodipin tab 5 mg">Amlodipin tab 5 mg</option>
<option value="Amlodipin tab 10 mg">Amlodipin tab 10 mg</option>
<option value="Atenolol tab 50 mg">Atenolol tab 50 mg</option>
<option value="Atenolol tab 100 mg">Atenolol tab 100 mg</option>
<option value="Bisoprolol tab 2,5 mg">Bisoprolol tab 2,5 mg</option>
<option value="Bisoprolol tab 5 mg">Bisoprolol tab 5 mg</option>
<option value="Bisoprolol tab 10 mg">Bisoprolol tab 10 mg</option>
<option value="Diltiazem kapsul lepas lambat 100 mg">Diltiazem kapsul lepas lambat 100 mg</option>
<option value="Diltiazem kapsul lepas lambat 200 mg">Diltiazem kapsul lepas lambat 200 mg</option>
<option value="Hidroklorotiazid tab 25 mg">Hidroklorotiazid tab 25 mg</option>
<option value="Imidapril tab 5 mg">Imidapril tab 5 mg</option>
<option value="Imidapril tab 10 mg">Imidapril tab 10 mg</option>
<option value="Irbesartan tab 150 mg">Irbesartan tab 150 mg</option>
<option value="Irbesartan tab 300 mg">Irbesartan tab 300 mg</option>
<option value="Kandesartan tab 8 mg">Kandesartan tab 8 mg</option>
<option value="Kandesartan tab 16 mg">Kandesartan tab 16 mg</option>
<option value="Kaptopril tab 12,5 mg">Kaptopril tab 12,5 mg</option>
<option value="Kaptopril tab 25 mg">Kaptopril tab 25 mg</option>
<option value="Kaptopril tab 50 mg">Kaptopril tab 50 mg</option>
<option value="Klonidin tab 0,15 mg">Klonidin tab 0,15 mg</option>
<option value="Lisinopril tab 5 mg">Lisinopril tab 5 mg</option>
<option value="Lisinopril tab 10 mg">Lisinopril tab 10 mg</option>
<option value="Metildopa tab 250 mg">Metildopa tab 250 mg</option>
<option value="Nifedipin tab 10 mg">Nifedipin tab 10 mg</option>
<option value="Furosemid tab 20 mg">Furosemid tab 20 mg</option>
<option value="Furosemid tab 40 mg">Furosemid tab 40 mg</option>
